PREFIX qb:   <http://purl.org/linked-data/cube#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX skos:  <http://www.w3.org/2004/02/skos/core#>


SELECT DISTINCT ?dimension ?code ?codeLabel WHERE {
	?dim a qb:DimensionProperty;
		rdfs:label ?dimension;
		qb:codeList ?codes.

  ?component qb:dimension ?dim.
  ?dsd qb:component ?component.

  ?dataSet qb:structure ?dsd.

	?codes skos:hasTopConcept ?code.
	?code skos:prefLabel ?codeLabel.
}