PREFIX qb:   <http://purl.org/linked-data/cube#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

SELECT DISTINCT ?dimension ?label WHERE{
  ?dimension a qb:DimensionProperty;
		rdfs:label ?label.

  ?component qb:dimension ?dimension.

  ?dataSet qb:component ?component.
}