PREFIX qb:   <http://purl.org/linked-data/cube#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

SELECT DISTINCT ?gene WHERE {
  [] a qb:ComponentSpecification;
    rdfs:label "Tumor_Sample_Barcode";
    qb:measure ?barcode_measure.

  ?patient_obs a qb:Observation;
    ?barcode_measure ?barcode;
    <http://onto.strinz.me/properties/patient_id> "%{patient}";
    <http://onto.strinz.me/properties/Hugo_Symbol> ?gene.


  #  ?node <http://semanticscience.org/resource/SIO_000300> ?gene ;  
}