SELECT distinct ?hgnc ?ensembl where {
 {?hgnc <http://bio2rdf.org/hgnc_vocabulary:approved_symbol> "%{hugo_symbol}"}
 UNION
 {?hgnc <http://bio2rdf.org/hgnc_vocabulary:synonym> "%{hugo_symbol}"}
 
 ?hgnc <http://bio2rdf.org/hgnc_vocabulary:x-ensembl> ?ensembl
}