PREFIX qb:   <http://purl.org/linked-data/cube#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX sio: <http://semanticscience.org/resource/>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>

SELECT DISTINCT ?column WHERE {
  [] a qb:ComponentSpecification;
    rdfs:label "%{column}";
    qb:measure ?column_measure.

  [] a qb:ComponentSpecification;
    rdfs:label "patient_id";
    qb:measure ?patient_id.

  ?obs a qb:Observation;
    ?patient_id "%{patient}" ;
    ?column_measure ?column.
 # {
 #   ?obs ?column_measure ?column.
 #   FILTER isLiteral(?column)
 # }
 # UNION
 # {?obs ?column_measure [ sio:SIO_000300 ?column ]}
 # UNION
 # {?obs ?column_measure [ sio:SIO_000008 [sio:SIO_000300 ?column] ]}
}