PREFIX qb:   <http://purl.org/linked-data/cube#> 
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#> 
PREFIX prop:  <http://www.rqtl.org/dc/properties/> 

SELECT DISTINCT ?observation ?property ?value WHERE{
	?observation a qb:Observation;
		?property ?value.

	{ ?property a qb:DimensionProperty. }
	UNION
	{ ?property a qb:MeasureProperty. }
}
