PREFIX qb:   <http://purl.org/linked-data/cube#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX sio: <http://semanticscience.org/resource/>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>

SELECT DISTINCT ?patient_id WHERE {
  [] a qb:ComponentSpecification;
    rdfs:label "Hugo_Symbol";
    qb:measure ?column_measure.

  [] a qb:ComponentSpecification;
    rdfs:label "patient_id";
    qb:measure ?patient_id_property.

  ?obs a qb:Observation;
    ?column_measure [ sio:SIO_000300 <http://identifiers.org/hgnc.symbol/%{hugo_symbol}> ];
    ?patient_id_property ?patient_id .
}