PREFIX qb:   <http://purl.org/linked-data/cube#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

SELECT (COUNT(?barcode) as ?barcodes) WHERE {
  [] a qb:ComponentSpecification;
    rdfs:label "Tumor_Sample_Barcode Component";
    qb:measure ?barcode_measure.

  ?patient_obs a qb:Observation;
    ?barcode_measure ?barcode.

  FILTER (regex(?barcode, "TCGA-%{patient}.*"))
}